title: "Archives of the Curious"
tagline: "Explorations into AI, science, learning, and curiosity-driven thinking."
description: "Personal blog by Sebastian Aguerre."
baseurl: ""
url: "https://sebasaguerre.github.io"

# Theme
remote_theme: "cotes2020/jekyll-theme-chirpy@v7.4.1"
paginate: 10

# Author info
author:
  name: "Sebastian Aguerre"
  #avatar: "/assets/img/profile.png"
  bio: "Curious mind exploring AI"
  location: "Netherlands"
  email: " "

# Navigation Menu (Top Bar)
navbar:
  - name: Home
    link: /
  - name: Projects
    link: /projects/
  - name: Tags
    link: /tags/
  - name: About
    link: /about/

#Enable search + math
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-archives
  - jekyll-feed
  - jekyll-paginate
  - jekyll-scholar
  - jekyll-include-cache
  - jekyll-mathjax
  #- jekyll-toc
  - jekyll-mathjax

markdown: kramdown

# Build settings
theme: null
